/**
 * The binary half of an avatar data URL.
 *
 * Kept away from IndexedDB so the conversion is cheap to unit-test in Node.
 * Avatars are generated by our own canvas as base64 JPEGs, but accepting the
 * percent-encoded form too makes the storage boundary honest for imported or
 * hand-edited backups.
 */
export interface AvatarBytes {
  type: string;
  bytes: Uint8Array;
}

export function decodeAvatarDataUrl(dataUrl: string): AvatarBytes | null {
  const comma = dataUrl.indexOf(",");
  if (!dataUrl.startsWith("data:") || comma < 0) return null;

  const header = dataUrl.slice(5, comma);
  const parts = header.split(";");
  const type = parts[0] === "" ? "application/octet-stream" : parts[0];
  const payload = dataUrl.slice(comma + 1);

  try {
    if (parts.includes("base64")) {
      const decoded = atob(payload);
      const bytes = new Uint8Array(decoded.length);
      for (let i = 0; i < decoded.length; i++) bytes[i] = decoded.charCodeAt(i);
      return { type, bytes };
    }

    return { type, bytes: new TextEncoder().encode(decodeURIComponent(payload)) };
  } catch {
    return null;
  }
}

export function sameBytes(left: Uint8Array, right: Uint8Array): boolean {
  if (left.byteLength !== right.byteLength) return false;
  for (let i = 0; i < left.byteLength; i++) {
    if (left[i] !== right[i]) return false;
  }
  return true;
}
